apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments # Match with 'matchLabels.app'
    spec:
      containers:
        - name: payments # Mainly for logging purposes
          image: 1997rishabhsingh/payments
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # client id = pod name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: "mongodb://payments-mongo-srv:27017/payments"
            - name: JWT_KEY # name that's visible to container (so could be anything)
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY # actual name of the key here
            - name: STRIPE_SECRET_KEY # name that's visible to container (so could be anything)
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_SECRET_KEY # actual name of the key here
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments # Match with 'spec.selector.template.metadata.labels.app'
  type: ClusterIP # Can be omitted since its default
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
