name: deploy-manifest

on:
  push:
    branches:
      - master
    paths:
      - "infra/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # uncomment to deploy on remote cluster
      # - uses: digitalocean/action-doctl@v2
      #   with:
      #     token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      # - run: doctl kubernetes cluster kubeconfig save ticketing # name of cluster
      # - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
